### PR TITLE
switch to openhtc.io servers if proxy is DIRECT

### PR DESCRIPTION
**Pull request by DrDaveD**
See [OO-215](https://jira.opensciencegrid.org/browse/OO-215)

### CODE REVIEW

**Comment by DrDaveD** [comment]
This is now installed in oasis-itb's config-osg.opensciencegrid.org if you want to test it.

**Comment by DrDaveD** [comment]
This is scheduled to be put into production Wednesday January 24 so please review before then.

**Comment by brianhlin** [comment]
> This is now installed in oasis-itb's config-osg.opensciencegrid.org if you want to test it.

Could you provide some guidance on this? I'm fuzzy on the details of the cvmfs config repo

**Comment by DrDaveD** [comment]
You can set `CVMFS_SERVER_URL="http://oasis-replica-itb.opensciencegrid.org:8000/cvmfs/@fqrn@"` in /etc/cvmfs/config.d/config-osg.opensciencegrid.org.local and verify after mounting with `sudo cvmfs_talk -i config-osg.opensciencegrid.org host info`.  You can use the same command on a different repo to verify whether or not you see servers in the openhtc.io domain.  They should be there when you set `CVMFS_HTTP_PROXY=DIRECT` in /etc/cvmfs/default.local, and not be there if you set the proxy to a squid URL.  In between tests you can use umount to unmount a repository and force it to reload the configuration, or test a different repository.

**Review by brianhlin — APPROVED** [review]
With the following:

```
# cat config.d/config-osg.opensciencegrid.org.local 
CVMFS_SERVER_URL="http://oasis-replica-itb.opensciencegrid.org:8000/cvmfs/@fqrn@"
# cat default.local 
CVMFS_REPOSITORIES="`echo $((echo oasis.opensciencegrid.org;echo cms.cern.ch;ls /cvmfs)|sort -u)|tr ' ' ,`"
CVMFS_QUOTA_LIMIT=20000
CVMFS_HTTP_PROXY=DIRECT
```

I see the `openhtc.io` references for `atlas.cern.ch`, `cms.cern.ch`, and `oasis.opensciencegrid.org`. I didn't see any `openhtc.io` references when I used the fermilab squid server.

**Pull request merged**
