### PR TITLE
Split lines

### PR DESCRIPTION
**Pull request by matyasselmeci**
Makes settings easier to read and modify

### CODE REVIEW

**Review by DrDaveD — CHANGES_REQUESTED** [review]
If you're going to change domain.d/osgstorage.org.conf, you should change at least also config.d/ligo.osgstorage.org.conf.  There's also default.conf and domain.d/cern.ch.conf.

Otherwise the changes look OK to me, but have you tested doing essentially the same things in `/etc/cvmfs/*.d/*.local` files?  This config repo immediately affects all OSG cvmfs clients so it should definitely be tested first (presumably by Marian) on oasis-itb, with a client that reads from it to make sure that access works with each config file changed and that the list of servers still look correct.  Use sudo cvmfs_talk -i repo.name host info and host external info.

**Comment by matyasselmeci** [comment]
Sounds good. I'll test things next week.

**Comment by DrDaveD** [comment]
@matyasselmeci This has been sitting here a year and a half, can we close this?

**Comment by matyasselmeci** [comment]
Yeah, it would be nice, but I'll most likely never get around to it.

**Pull request closed without merging**
