### PR TITLE
add Chicago and New York I2 cache; #OO-247

### PR DESCRIPTION
**Pull request by zvada**

### CODE REVIEW

**Comment by DrDaveD** [comment]
The change itself looks ok, but it has to wait until the FNAL & BNL stratum 1s are upgraded to cvmfs-server-2.5.1, as discussed in OO-247.

**Comment by zvada** [comment]
We won't do manual changes before all stratum 1s upgrade on live machines, but why it can't go to the repo? Repo and deployed configs are not in sync unless we re-install from scratch, is that correct?

**Comment by DrDaveD** [comment]
Actually there's no automated mechanism tying the github repo with what is deployed in /cvmfs/config-osg.opensciencegrid.org.   Still, I think it's better to not to merge this into github until it is ready to be deployed.  Something else might come along in the meantime that needs to be deployed and it might get accidentally released with it.  We don't know how long it will take FNAL & BNL to upgrade.  We can just leave it pending in the PR.

**Comment by zvada** [comment]
Yeah, that's what I meant by 'Repo' as GitHub repo not in sync what's deployed in `/cvmfs/config-osg.opensciencegrid.org`. Sure, we can leave PR pending until everybody upgrades, though.

**Comment by brianhlin** [comment]
Are FNAL/BNL still backversioned on CVMFS?

**Comment by DrDaveD** [comment]
FNAL is upgraded, but as far as I have heard, BNL is not yet.

**Comment by zvada** [comment]
BNL upgraded, too. Could we proceed with approval, @DrDaveD ?

**Review by DrDaveD — APPROVED** [review]
We're good to go

**Pull request merged**
