### PR TITLE
a few small updates to the oasis install scripts

### PR DESCRIPTION
**Pull request by DrDaveD**
1. automatically sign whitelists on semi-monthly on oasis-itb
2. use curl instead of wget on ecsft.cern.ch, for new hostcert with SAN
3. add commented-out code for use with cvmfs-server-2.2.0

### CODE REVIEW

**Comment by DrDaveD** [comment]
@bbockelm Can you please merge this pull request?

**Comment by bbockelm** [comment]
What motivates the switch from `wget` to `curl`?  Anything in particular?

**Comment by DrDaveD** [comment]
As the commit message said, it was for the new hostcert with SAN (Subject Alternative Name).  Wget doesn't support that, at least on el5.

**Comment by bbockelm** [comment]
Ah, I missed the commit message.

Looks good to me then.

**Pull request merged**
