### PR TITLE
add KISTI StashCache

### PR DESCRIPTION
**Pull request by zvada**

### CODE REVIEW

**Comment by zvada** [comment]
@DrDaveD, could you review, please?

**Comment by DrDaveD** [comment]
Do they use OSG configuration at KISTI?  Do they use EGI?

**Comment by zvada** [comment]
I believe KIST uses OSG configuration. @efajardo, can you confirm?

**Comment by efajardo** [comment]
Yes they do

**Review by DrDaveD — APPROVED** [review]

**Pull request merged**
