### PR TITLE
add I2 caches to config.d/ligo.osgstorage.org.conf; #STAS-49

### PR DESCRIPTION
**Pull request by zvada**

### CODE REVIEW

**Comment by DrDaveD** [comment]
Do you know if those caches do indeed support ligo, did you test them?  The list is a lot shorter for ligo.

**Comment by zvada** [comment]
Yes, they should support LIGO, those are authenticated caches, I trust @efajardo he has tested them and they are good to go. @efajardo?

**Comment by efajardo** [comment]
Yes I did test them. You can see [here](https://gracc.opensciencegrid.org/kibana/app/kibana#/dashboard/AWG5ztK58IKqxDdAglqh?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(description:'',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWG5Vxjr4SibPatHSRAw,key:server_hostname.keyword,negate:!f,type:phrase,value:osg.newy32aoa.nrp.internet2.edu),query:(match:(server_hostname.keyword:(query:osg.newy32aoa.nrp.internet2.edu,type:phrase))))),options:(darkTheme:!f),panels:!((col:1,id:AWG5Aphc8IKqxDdAglqg,panelIndex:1,row:1,size_x:6,size_y:5,type:visualization),(col:7,id:AWG5z7gs8IKqxDdAglqi,panelIndex:2,row:1,size_x:6,size_y:3,type:visualization),(col:1,id:AWG53PR88IKqxDdAglqj,panelIndex:3,row:6,size_x:12,size_y:6,type:visualization),(col:1,id:AWG-ZL-88IKqxDdAglqk,panelIndex:4,row:17,size_x:6,size_y:3,type:visualization),(col:1,id:AWIrOP7H8IKqxDdAglqm,panelIndex:6,row:12,size_x:12,size_y:5,type:visualization)),query:(match_all:()),timeRestore:!f,title:StashCache,uiState:(P-1:(vis:(params:(sort:(columnIndex:2,direction:desc)))),P-2:(vis:(defaultColors:('0%20-%20100':'rgb(0,104,55)'))),P-4:(vis:(params:(sort:(columnIndex:!n,direction:!n))))),viewMode:view))

And [here](https://gracc.opensciencegrid.org/kibana/app/kibana#/dashboard/AWG5ztK58IKqxDdAglqh?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(description:'',filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWG5Vxjr4SibPatHSRAw,key:server_hostname.keyword,negate:!f,type:phrase,value:osg.kans.nrp.internet2.edu),query:(match:(server_hostname.keyword:(query:osg.kans.nrp.internet2.edu,type:phrase))))),options:(darkTheme:!f),panels:!((col:1,id:AWG5Aphc8IKqxDdAglqg,panelIndex:1,row:1,size_x:6,size_y:5,type:visualization),(col:7,id:AWG5z7gs8IKqxDdAglqi,panelIndex:2,row:1,size_x:6,size_y:3,type:visualization),(col:1,id:AWG53PR88IKqxDdAglqj,panelIndex:3,row:6,size_x:12,size_y:6,type:visualization),(col:1,id:AWG-ZL-88IKqxDdAglqk,panelIndex:4,row:17,size_x:6,size_y:3,type:visualization),(col:1,id:AWIrOP7H8IKqxDdAglqm,panelIndex:6,row:12,size_x:12,size_y:5,type:visualization)),query:(match_all:()),timeRestore:!f,title:StashCache,uiState:(P-1:(vis:(params:(sort:(columnIndex:2,direction:desc)))),P-2:(vis:(defaultColors:('0%20-%20100':'rgb(0,104,55)'))),P-4:(vis:(params:(sort:(columnIndex:!n,direction:!n))))),viewMode:view)). That indeed they are working for the secure LIGO part.

**Comment by DrDaveD** [comment]
Ok, well if you want we could add kansas city now, but the others need to wait until BNL & FNAL stratum 1s are upgraded.

**Comment by zvada** [comment]
I did add KC for now.

**Comment by brianhlin** [comment]
Same question as https://github.com/opensciencegrid/oasis-server/pull/95#issuecomment-431481306

**Comment by DrDaveD** [comment]
[Same answer](https://github.com/opensciencegrid/oasis-server/pull/95#issuecomment-431498698)

**Comment by zvada** [comment]
BNL updated and port for I2 authenticated caches fixed to 8444. Could we proceed with approval, @DrDaveD ?

**Comment by zvada** [comment]
@DrDaveD, could you take a look at this PR and review, please?

**Review by DrDaveD — APPROVED** [review]
Looks good

**Pull request merged**
